// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tenant

import (
	"goframe-vben/api/tenant"
)

type ControllerAdmin struct{}

func NewAdmin() tenant.ITenantAdmin {
	return &ControllerAdmin{}
}
