// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"goframe-vben/addons/example/api/user"
)

type ControllerAdmin struct{}

func NewAdmin() user.IUserAdmin {
	return &ControllerAdmin{}
}
