// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"goframe-vben/api/admin"
)

type ControllerAuth struct{}

func NewAuth() admin.IAdminAuth {
	return &ControllerAuth{}
}

type ControllerRole struct{}

func NewRole() admin.IAdminRole {
	return &ControllerRole{}
}

type ControllerMenu struct{}

func NewMenu() admin.IAdminMenu {
	return &ControllerMenu{}
}

type ControllerUser struct{}

func NewUser() admin.IAdminUser {
	return &ControllerUser{}
}

type ControllerCommon struct{}

func NewCommon() admin.IAdminCommon {
	return &ControllerCommon{}
}

type ControllerConfig struct{}

func NewConfig() admin.IAdminConfig {
	return &ControllerConfig{}
}

type ControllerCron struct{}

func NewCron() admin.IAdminCron {
	return &ControllerCron{}
}

type ControllerDict struct{}

func NewDict() admin.IAdminDict {
	return &ControllerDict{}
}

type ControllerOperationrecord struct{}

func NewOperationrecord() admin.IAdminOperationrecord {
	return &ControllerOperationrecord{}
}

type ControllerLoginrecord struct{}

func NewLoginrecord() admin.IAdminLoginrecord {
	return &ControllerLoginrecord{}
}

type ControllerOrganization struct{}

func NewOrganization() admin.IAdminOrganization {
	return &ControllerOrganization{}
}
