// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"github.com/gogf/gf/v2/util/gconv"
	"goframe-vben/api"
	"goframe-vben/internal/model/entity"
	"sort"
)

// ConvertToTree converts a flat list of menus to a tree structure
func ConvertToTree(menus []*entity.SysMenu) []*api.MenuTree {
	menuMap := make(map[int64]*api.MenuTree)
	var roots []*api.MenuTree

	// Create a map of menus
	for i := range menus {
		var temp api.MenuTree
		if err := gconv.Struct(menus[i], &temp); err != nil {
			return nil
		}

		menuMap[menus[i].Id] = &temp
	}

	// Build the tree
	for id, menu := range menuMap {
		if parent, exists := menuMap[menu.ParentId]; exists {
			parent.Children = append(parent.Children, menu)
		} else {
			roots = append(roots, menuMap[id])
		}
	}

	// 对每个节点的子菜单进行排序
	var sortMenus func(menus []*api.MenuTree)
	sortMenus = func(menus []*api.MenuTree) {
		sort.Slice(menus, func(i, j int) bool {
			return menus[i].Sort < menus[j].Sort
		})
		for _, menu := range menus {
			sortMenus(menu.Children)
		}
	}

	sortMenus(roots)

	return roots
}
