// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// payOrderDao is the data access object for the table pay_order.
// You can define custom methods on it to extend its functionality as needed.
type payOrderDao struct {
	*internal.PayOrderDao
}

var (
	// PayOrder is a globally accessible object for table pay_order operations.
	PayOrder = payOrderDao{internal.NewPayOrderDao()}
)

// Add your custom methods and functionality below.
