// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// payOrderExtensionDao is the data access object for the table pay_order_extension.
// You can define custom methods on it to extend its functionality as needed.
type payOrderExtensionDao struct {
	*internal.PayOrderExtensionDao
}

var (
	// PayOrderExtension is a globally accessible object for table pay_order_extension operations.
	PayOrderExtension = payOrderExtensionDao{internal.NewPayOrderExtensionDao()}
)

// Add your custom methods and functionality below.
