// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysMenuTempDao is the data access object for the table sys_menu_temp.
// You can define custom methods on it to extend its functionality as needed.
type sysMenuTempDao struct {
	*internal.SysMenuTempDao
}

var (
	// SysMenuTemp is a globally accessible object for table sys_menu_temp operations.
	SysMenuTemp = sysMenuTempDao{internal.NewSysMenuTempDao()}
)

// Add your custom methods and functionality below.
