// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysEmailRecordDao is the data access object for the table sys_email_record.
// You can define custom methods on it to extend its functionality as needed.
type sysEmailRecordDao struct {
	*internal.SysEmailRecordDao
}

var (
	// SysEmailRecord is a globally accessible object for table sys_email_record operations.
	SysEmailRecord = sysEmailRecordDao{internal.NewSysEmailRecordDao()}
)

// Add your custom methods and functionality below.
