// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysFileRecordDao is the data access object for the table sys_file_record.
// You can define custom methods on it to extend its functionality as needed.
type sysFileRecordDao struct {
	*internal.SysFileRecordDao
}

var (
	// SysFileRecord is a globally accessible object for table sys_file_record operations.
	SysFileRecord = sysFileRecordDao{internal.NewSysFileRecordDao()}
)

// Add your custom methods and functionality below.
