// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysTenantPackageDao is the data access object for the table sys_tenant_package.
// You can define custom methods on it to extend its functionality as needed.
type sysTenantPackageDao struct {
	*internal.SysTenantPackageDao
}

var (
	// SysTenantPackage is a globally accessible object for table sys_tenant_package operations.
	SysTenantPackage = sysTenantPackageDao{internal.NewSysTenantPackageDao()}
)

// Add your custom methods and functionality below.
