// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysLoginRecordDao is the data access object for the table sys_login_record.
// You can define custom methods on it to extend its functionality as needed.
type sysLoginRecordDao struct {
	*internal.SysLoginRecordDao
}

var (
	// SysLoginRecord is a globally accessible object for table sys_login_record operations.
	SysLoginRecord = sysLoginRecordDao{internal.NewSysLoginRecordDao()}
)

// Add your custom methods and functionality below.
