// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysOperationRecordDao is the data access object for the table sys_operation_record.
// You can define custom methods on it to extend its functionality as needed.
type sysOperationRecordDao struct {
	*internal.SysOperationRecordDao
}

var (
	// SysOperationRecord is a globally accessible object for table sys_operation_record operations.
	SysOperationRecord = sysOperationRecordDao{internal.NewSysOperationRecordDao()}
)

// Add your custom methods and functionality below.
