// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysConfigModuleDao is the data access object for the table sys_config_module.
// You can define custom methods on it to extend its functionality as needed.
type sysConfigModuleDao struct {
	*internal.SysConfigModuleDao
}

var (
	// SysConfigModule is a globally accessible object for table sys_config_module operations.
	SysConfigModule = sysConfigModuleDao{internal.NewSysConfigModuleDao()}
)

// Add your custom methods and functionality below.
