// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysConfigItemDao is the data access object for the table sys_config_item.
// You can define custom methods on it to extend its functionality as needed.
type sysConfigItemDao struct {
	*internal.SysConfigItemDao
}

var (
	// SysConfigItem is a globally accessible object for table sys_config_item operations.
	SysConfigItem = sysConfigItemDao{internal.NewSysConfigItemDao()}
)

// Add your custom methods and functionality below.
