// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysCronRecordDao is the data access object for the table sys_cron_record.
// You can define custom methods on it to extend its functionality as needed.
type sysCronRecordDao struct {
	*internal.SysCronRecordDao
}

var (
	// SysCronRecord is a globally accessible object for table sys_cron_record operations.
	SysCronRecord = sysCronRecordDao{internal.NewSysCronRecordDao()}
)

// Add your custom methods and functionality below.
