// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-vben/internal/dao/internal"
)

// sysOrganizationDao is the data access object for the table sys_organization.
// You can define custom methods on it to extend its functionality as needed.
type sysOrganizationDao struct {
	*internal.SysOrganizationDao
}

var (
	// SysOrganization is a globally accessible object for table sys_organization operations.
	SysOrganization = sysOrganizationDao{internal.NewSysOrganizationDao()}
)

// Add your custom methods and functionality below.
