// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tenant_package

import (
	"goframe-vben/api/tenant_package"
)

type ControllerAdmin struct{}

func NewAdmin() tenant_package.ITenantPackageAdmin {
	return &ControllerAdmin{}
}
